services:
  - type: web
    name: tracking-mr
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tracking-mr-db
          property: connectionString
    plan: free
    autoDeploy: true
    healthCheckPath: /status
    healthCheckTimeoutSeconds: 10
    healthCheckIntervalSeconds: 60

databases:
  - name: tracking-mr-db
    plan: free