services:
  - type: web
    name: pixel-tracker
    env: python
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pixel-tracking-db
          property: connectionString

databases:
  - name: pixel-tracking-db
    plan: free
