services:
  - type: web
    name: pixel-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pixel-db
          property: connectionString
databases:
  - name: pixel-db
