services:
  - type: web
    name: tracking-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tracking-db
          property: connectionString

databases:
  - name: tracking-db
    plan: free